---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations:
      fabric8.io/iconUrl: "img/icons/activemq.svg"
      fabric8.io/git-commit: "98abfe54240458b18bf553a2f0403ca4bfd57868"
      fabric8.io/git-branch: "release-v2.2.148"
      fabric8.io/build-id: "1"
      fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/98abfe54240458b18bf553a2f0403ca4bfd57868"
      fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/1"
    labels:
      provider: "fabric8"
      group: "io.fabric8.ipaas.apps"
      project: "message-broker"
      version: "2.2.148"
    name: "message-broker"
  spec:
    ports:
    - port: 61616
      protocol: "TCP"
      targetPort: 61616
    selector:
      provider: "fabric8"
      group: "io.fabric8.ipaas.apps"
      project: "message-broker"
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    annotations:
      fabric8.io/iconUrl: "img/icons/activemq.svg"
      fabric8.io/git-commit: "98abfe54240458b18bf553a2f0403ca4bfd57868"
      fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=message-broker&var-version=2.2.148"
      fabric8.io/build-id: "1"
      fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/1"
      fabric8.io/git-branch: "release-v2.2.148"
      fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/98abfe54240458b18bf553a2f0403ca4bfd57868"
    labels:
      provider: "fabric8"
      group: "io.fabric8.ipaas.apps"
      project: "message-broker"
      version: "2.2.148"
    name: "message-broker"
  spec:
    replicas: 1
    selector:
      provider: "fabric8"
      group: "io.fabric8.ipaas.apps"
      project: "message-broker"
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: "98abfe54240458b18bf553a2f0403ca4bfd57868"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=message-broker&var-version=2.2.148"
          fabric8.io/build-id: "1"
          fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/1"
          fabric8.io/iconUrl: "img/icons/activemq.svg"
          fabric8.io/git-branch: "release-v2.2.148"
          fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/98abfe54240458b18bf553a2f0403ca4bfd57868"
        labels:
          provider: "fabric8"
          group: "io.fabric8.ipaas.apps"
          project: "message-broker"
          version: "2.2.148"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/amqbroker:2.2.96"
          imagePullPolicy: "IfNotPresent"
          name: "message-broker"
          ports:
          - containerPort: 61616
            name: "amq"
          - containerPort: 8778
            name: "jolokia"
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
    triggers:
    - type: "ConfigChange"
kind: "List"
